version: "3"
services:
  simple_jupyter_231225:
    container_name: simple_jupyter_231225
    build:
      context: ./.docker/python
      args:
        ENV_NAME: $ENV_NAME
    volumes:
      - ./:/app
    ports:
      - $WEB_PORT:8888
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''
